DEVICE_IP_INPUT = "ip-input"
DEVICE_PORT_INPUT = "port-input"
DEVICE_NAME_INPUT = "device-name-input"
RTS_NAME_INPUT = "rts-name-input"
RTS_PORT_INPUT = "rts-port-input"
RTS_BAUDRATE_INPUT = "rts-baudrate-input"
RTS_TIMEOUT_INPUT = "rts-timeout-input"
RTS_PARITY_INPUT = "rts-parity-input"
RTS_STOPBITS_INPUT = "rts-stopbits-input"
RTS_BYTESIZE_INPUT = "rts-bytesize-input"
CREATE_RTS_BUTTON = "create-rts-button"
CREATE_DEVICE_BUTTON = "create-device-button"
OPEN_DEVICE_MODAL_BUTTON = "device-modal-button"
OPEN_RTS_MODAL_BUTTON = "rts-modal-button"
DEVICE_DROPDOWN = "device-dropdown"

CLOSE_DEVICE_MODAL_BUTTON = "close-device-modal-button"
DEVICE_MODAL = "device-modal"

CLOSE_RTS_MODAL_BUTTON = "close-rts-modal-button"
RTS_MODAL = "rts-modal"

DEVICE_LIST = "device-list"
REFRESH = "refresh"
RTS_LIST = "rts-list"
PROGRESS_BAR = "progress-bar"
LOADING = "loading"

INVALID_DEVICE_INPUT_ALERT = "invalid-input-alert"
INVALID_RTS_INPUT_ALERT = "invalid-rts-input-alert"
INVALID_SETTINGS_INPUT_ALERT = "invalid-settings-input-alert"
INVALID_SCAN_INPUT_ALERT = "invalid-scan-input-alert"

START_ALL_BUTTON = "start-all-button"
STOP_ALL_BUTTON = "stop-all-button"

DUMMY_OUTPUT = "dummy-output"

DEVICE_STORAGE = "device-storage"
RTS_POSITION_STORAGE = "rts-position-storage"
TARGET_POSITION = "target-position"
DEVICE_COUNT = "device-count"

RTS_UPDATE_SIGNAL = "rts-update-signal"

SETTINGS_MODAL = "settings-modal"
SETTINGS_MODAL_BODY = "settings-modal-body"
APPLY_SETTINGS_MODAL_BUTTON = "apply-settings-modal-button"
CLOSE_SETTINGS_MODAL_BUTTON = "close-settings-modal-button"
SETTINGS_FORM = "settings-form"

RTS_MEASUREMENT_MODE = "rts-measurement-mode"
RTS_INCLINATION_MODE = "rts-inclination-mode"
RTS_EDM_MODE = "rts-edm-mode"
RTS_PRISM_TYPE = "rts-prism-type"
RTS_FINE_ADJUST_HORIZONTAL_SEARCH_RANGE = "rts-fine-adjust-horizontal-search-range"
RTS_FINE_ADJUST_VERTICAL_SEARCH_RANGE = "rts-fine-adjust-vertical-search-range"
RTS_POWER_SEARCH_RANGE = "rts-power-search-range"
RTS_POWER_SEARCH_ENABLED = "rts-power-search-enabled"

ACTIVE_RTS = "active-rts"
ACTIVE_DEVICE = "active-device"

LOG_DOWNLOAD = "log-download"
LOG_DROPDOWN = "log-dropdown"
DOWNLOAD_LOG = "download-log"
DELETE_LOG = "delete-log"
CLOSE_LOG_MODAL_BUTTON = "close-log-modal-button"
LOG_MODAL = "log-modal"

CURRENT_TARGET_POSITION = "current-target-position"
CURRENT_TARGET_DEVICE = "current-target-device"

SCAN_MODAL = "scan-modal"
SCAN_DEVICE_BUTTON = "scan-device-button"
CLOSE_SCAN_MODAL_BUTTON = "close-scan-modal-button"
NETWORK_INPUT = "network-input"
NETWORK_PORT_INPUT = "network-port-input"
OPEN_SCAN_MODAL_BUTTON = "open-scan-modal-button"
SCAN_DEVICE_LOADING = "scan-device-loading"
